spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://sql7.freemysqlhosting.net:3306/sql7282808
    username: sql7282808
    password: ZWzWCxQHYf
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true